# Generated by Django 6.0.3 on 2026-04-17 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this credential', unique=True)),
                ('practitioner_name', models.CharField(help_text='Full name of the medical practitioner', max_length=255)),
                ('practitioner_id', models.CharField(help_text='National ID or passport number of the practitioner', max_length=100, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(help_text='e.g. MBChB, BDS, MMed', max_length=255)),
                ('specialization', models.CharField(blank=True, help_text='e.g. Surgery, Paediatrics, Dentistry', max_length=255, null=True)),
                ('institution_of_study', models.CharField(help_text='University or institution where qualification was obtained', max_length=255)),
                ('year_of_graduation', models.IntegerField(help_text='Year the practitioner graduated')),
                ('license_number', models.CharField(help_text='UMDPC license number', max_length=100, unique=True)),
                ('license_expiry_date', models.DateField(help_text='Date the practicing license expires')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Ethereum transaction hash from credential registration', max_length=66, null=True)),
                ('blockchain_recorded_at', models.DateTimeField(blank=True, help_text='When this credential was recorded on the blockchain', null=True)),
                ('ipfs_document_hash', models.CharField(blank=True, help_text='IPFS content hash (CID) of the credential document', max_length=255, null=True)),
                ('ipfs_photo_hash', models.CharField(blank=True, help_text='IPFS content hash (CID) of the practitioner photo', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(help_text='The user who registered this credential', on_delete=django.db.models.deletion.PROTECT, related_name='credentials_issued', to=settings.AUTH_USER_MODEL)),
                ('issuing_institution', models.ForeignKey(blank=True, help_text='The institution that issued this credential', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credentials_issued', to='accounts.institution')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queried_credential_id', models.CharField(help_text='The credential ID or license number that was queried', max_length=100)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVOKED', 'Credential Revoked'), ('NOT_FOUND', 'Credential Not Found'), ('FACE_MISMATCH', 'Face Mismatch')], max_length=20)),
                ('face_match', models.BooleanField(default=False, help_text='Whether the biometric face check passed')),
                ('face_match_score', models.FloatField(blank=True, help_text='Confidence score of face match (0.0 to 1.0)', null=True)),
                ('blockchain_verified', models.BooleanField(default=False, help_text='Whether the blockchain record confirmed the credential')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the verification request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser and device information', null=True)),
                ('flagged_as_suspicious', models.BooleanField(default=False, help_text='Whether AI fraud detection flagged this attempt')),
                ('fraud_score', models.FloatField(blank=True, help_text='AI fraud risk score (higher = more suspicious)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='credentials.credential')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
