# Generated by Django 4.2.7 on 2026-05-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='last_renewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent renewal', null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='renewal_count',
            field=models.IntegerField(default=0, help_text='Number of times this credential has been renewed'),
        ),
    ]
