# Generated by Django 4.2.7 on 2026-05-16 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_APPROVED', 'User Approved'), ('USER_REJECTED', 'User Rejected'), ('CREDENTIAL_ISSUED', 'Credential Issued'), ('CREDENTIAL_REVOKED', 'Credential Revoked'), ('CREDENTIAL_RENEWED', 'Credential Renewed'), ('CREDENTIAL_EXPIRED', 'Credential Marked Expired'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed')], max_length=40)),
                ('target_type', models.CharField(blank=True, help_text="Model name of the affected object (e.g. 'CustomUser', 'Credential')", max_length=50)),
                ('target_id', models.CharField(blank=True, help_text='PK or UUID of the affected object', max_length=100)),
                ('target_description', models.CharField(blank=True, help_text='Human-readable summary of the affected object', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Extra context or reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
