# Generated by Django 4.2.7 on 2026-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_security_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_APPROVED', 'User Approved'), ('USER_REJECTED', 'User Rejected'), ('CREDENTIAL_ISSUED', 'Credential Issued'), ('CREDENTIAL_REVOKED', 'Credential Revoked'), ('CREDENTIAL_RENEWED', 'Credential Renewed'), ('CREDENTIAL_EXPIRED', 'Credential Marked Expired'), ('LOGIN_SUCCESS', 'Login Successful'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logged Out'), ('ACCOUNT_LOCKED', 'Account Locked'), ('2FA_SETUP_COMPLETE', '2FA Setup Completed'), ('2FA_VERIFIED', '2FA Verified on Login'), ('TOTP_RESET', 'Admin Reset User 2FA'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('EMAIL_VERIFIED', 'Email Address Verified'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institution_name',
            field=models.CharField(blank=True, help_text='Display name — auto-populated from institution FK when set', max_length=255, null=True),
        ),
    ]
